# Travis Configuration for SVARBlockMC.py
#

sudo: false        #Use new Container Infrastructure
language: python

cache:
  pip: true
  directories:
    # osx-specific caches
    - $HOME/Library/Caches/pip

dist: xenial

language: python

python: 
    - "3.7"

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels conda-forge

install:
  - pip install -U pip scipy jax jaxlib pytest flake8 codecov pytest-cov
  - python setup.py install

script:
  - flake8 --select F401, F405,E231 svar_block_MC
  - pytest --cov=svar_block_mc

after_success:
  - codecov

